ifneq ($(TOOLCHAIN),)
    CMAKE_FLAGS	+=-DCMAKE_TOOLCHAIN_FILE=$(TOPDIR)/script/toolchain/$(TOOLCHAIN).cmake
endif

ifneq ($(INSTALL_PREFIX),)
    CMAKE_FLAGS	+=-DCMAKE_INSTALL_PREFIX=$(INSTALL_PREFIX)
endif

ifneq ($(WITH_COMPILER_WARNINGS),)
    CMAKE_FLAGS	+=-DWITH_COMPILER_WARNINGS=$(WITH_COMPILER_WARNINGS)
endif

ifneq ($(WITH_CPPCHECK),)
    CMAKE_FLAGS	+=-DWITH_CPPCHECK=$(WITH_CPPCHECK)
endif

ifneq ($(WITH_CPPCHECK_MISRA),)
    CMAKE_FLAGS	+=-DWITH_CPPCHECK_MISRA=$(WITH_CPPCHECK_MISRA)
endif

ifneq ($(WITH_CPPCHECK_WARNINGS_AS_ERRORS),)
    CMAKE_FLAGS	+=-DWITH_CPPCHECK_WARNINGS_AS_ERRORS=$(WITH_CPPCHECK_WARNINGS_AS_ERRORS)
endif

ifneq ($(CPPCHECK_MISRA_RULE_TEXTS),)
    CMAKE_FLAGS	+=-DCPPCHECK_MISRA_RULE_TEXTS=$(CPPCHECK_MISRA_RULE_TEXTS)
endif

ifneq ($(WITH_TEST_APP),)
    CMAKE_FLAGS	+=-DWITH_TEST_APP=$(WITH_TEST_APP)
endif

ifneq ($(WITH_SIMD),)
    CMAKE_FLAGS	+=-DWITH_SIMD=$(WITH_SIMD)
endif

ifneq ($(WITH_THREAD),)
    CMAKE_FLAGS	+=-DWITH_THREAD=$(WITH_THREAD)
endif

ifneq ($(V),0)
    VERBOSE	:=-v
endif

ifeq ($(TOOLCHAIN),gnu)
    HOSTENV=TRUE
endif

ifeq ($(TOOLCHAIN),llvm)
    HOSTENV=TRUE
endif
