# SPDX-License-Identifier: MIT
#
# Copyright (c) 2025 Dylan Hong
#
# This file is released under the MIT License.
# For conditions of distribution and use, see the LICENSE file.

TOPDIR			:=$(dir $(abspath $(firstword $(MAKEFILE_LIST))))
WORKSPACE		:=$(TOPDIR)
BUILD_ROOT		:=$(TOPDIR)/build
BUILD			?=$(BUILD_ROOT)/$(TOOLCHAIN)
PROFILE_BUILD		?=$(BUILD_ROOT)/profile-lttng/$(TOOLCHAIN)
CMAKE			:=cmake
CTEST			:=ctest
CPACK			:=cpack
CPPCHECK_REPORT	?=$(TOPDIR)/script/cppcheck-report.sh
NPROC			?=$(shell nproc)
CTEST_ARGS		?=--output-on-failure
PROFILE_KERNEL	?=0
PROFILE_REPEAT_COUNT	?=1
PROFILE_WARMUP_COUNT	?=0

# Verbose output
#   Supported values:
#	0: quiet
#	1: verbose
V				?=0

# Build Type
#   Supported values:
#     Debug
#     Release
#     RelWithDebInfo
#     MinSizeRel
BUILD_TYPE		?=Release
WITH_BENCHMARK_COMPARE	?=ON

# Cross-compile options:
#   TOOLCHAIN selects the CMake toolchain file used for building.
#   Supported values:
#     llvm
#     gnu
#     aarch64-none-linux-llvm
#     aarch64-none-linux-gnu
#
# Example:
#   make TOOLCHAIN=gnu
#
TOOLCHAIN		?=llvm

# Target Name
TARGET			?=resize
INPUT			?=$(TOPDIR)/resource/sample.png
OUTPUT			?=$(BUILD_ROOT)/output
ARGS			?=$(INPUT) $(OUTPUT)

# include the common configuration file
include $(TOPDIR)/config.mk

# Default entry point: configure if needed, then build every enabled target.
all: build

# Generate or refresh the CMake build tree from Makefile/cache variables.
phony+=config
config:
	$(CMAKE) $(CMAKE_FLAGS) -DCMAKE_BUILD_TYPE=$(BUILD_TYPE) -S$(WORKSPACE) -B$(BUILD)

# Compile the configured project with the selected parallel job count.
phony+=build
build: config
	$(CMAKE) --build $(BUILD) -j $(NPROC) $(VERBOSE)

# Build and run every CTest entry in the selected build tree.
phony+=test
test: build
	$(CTEST) --test-dir $(BUILD) $(CTEST_ARGS)

# Install exported libraries, headers, and package metadata to the CMake prefix.
phony+=install
install:
	$(CMAKE) --install $(BUILD) $(VERBOSE)

# Build binary package archives using CPack metadata generated by CMake.
phony+=package
package:
	$(CPACK) --config $(BUILD)/CPackConfig.cmake $(VERBOSE)

# Build source package archives using CPack's source configuration.
phony+=package-source
package-source:
	$(CPACK) --config $(BUILD)/CPackSourceConfig.cmake $(VERBOSE)

# Remove object files and generated build outputs while keeping CMake cache.
phony+=clean
clean:
	$(CMAKE) --build $(BUILD) --target clean $(VERBOSE)

# Remove every generated build tree, including per-toolchain caches and shared outputs.
phony+=distclean
distclean:
	rm -rf $(BUILD_ROOT)

# Build and run TARGET with ARGS through CMake's generated run wrapper.
phony+=run
run: build
	RUN_TARGET=$(TARGET) ARGS="$(ARGS)" $(CMAKE) --build $(BUILD) --target run

# Refresh the benchmark CSV plus representative and channel-specific SVGs.
phony+=benchmark-update benchmark-svg
benchmark-update: config
	$(CMAKE) --build $(BUILD) --target benchmark-update -j $(NPROC) $(VERBOSE)

# Compatibility alias for the previous snapshot-only Make target.
benchmark-svg: benchmark-update

# Build an LTTng-UST instrumented resize binary and record a CTF trace.
phony+=profile-lttng
profile-lttng:
	$(CMAKE) $(CMAKE_FLAGS) -DWITH_LTTNG=ON \
		-DSGL_TEST_RESIZE_REPEAT_COUNT=$(PROFILE_REPEAT_COUNT) \
		-DSGL_TEST_RESIZE_WARMUP_COUNT=$(PROFILE_WARMUP_COUNT) \
		-DCMAKE_BUILD_TYPE=$(BUILD_TYPE) -S$(WORKSPACE) -B$(PROFILE_BUILD)
	SGL_LTTNG_KERNEL=$(PROFILE_KERNEL) $(CMAKE) --build $(PROFILE_BUILD) --target profile-lttng -j $(NPROC) $(VERBOSE)

# Print runnable test applications and their expected command-line arguments.
phony+=list-tests
list-tests: config
	$(CMAKE) --build $(BUILD) --target list-test-apps

# Run the standalone cppcheck report flow with the same analysis options as CMake.
phony+=cppcheck-report
cppcheck-report: config
	BUILD_DIR=$(BUILD) REPORT_ROOT=$(TOPDIR)/report WITH_CPPCHECK_MISRA=$(WITH_CPPCHECK_MISRA) CPPCHECK_MISRA_RULE_TEXTS="$(CPPCHECK_MISRA_RULE_TEXTS)" CPPCHECK_MAX_CTU_DEPTH=$(CPPCHECK_MAX_CTU_DEPTH) CPPCHECK_JOBS=$(NPROC) $(CPPCHECK_REPORT)

.PHONY: $(phony)
