option(WITH_COMPILER_WARNINGS           "Enable common compiler warnings"           ON)
option(WITH_CPPCHECK                    "Enable cppcheck static analysis"           ON)
option(WITH_CPPCHECK_MISRA              "Enable cppcheck MISRA C:2012 addon"        ON)
option(WITH_CPPCHECK_WARNINGS_AS_ERRORS "Treat cppcheck findings as build errors"   ON)
option(WITH_TEST_APP                    "Enable Test Application Feature"           ON)
option(WITH_SIMD                        "Enable SIMD Feature"                       ON)
option(WITH_THREAD                      "Enable Thread Feature"                     ON)
set(CPPCHECK_MISRA_RULE_TEXTS           "" CACHE FILEPATH "Optional path to the licensed MISRA C rule headlines file")